/**
 * @file test_codegen.cpp
 * @brief Unit tests for the Code Generator module
 * 
 * This file contains comprehensive tests for code generation,
 * testing C code output, type translation, and instruction mapping.
 */

#define CATCH_CONFIG_MAIN
#include "catch2/catch.hpp"
#include "codegen/code_generator.h"
#include "ir/ir_generator.h"
#include "semantic/semantic_analyzer.h"
#include "parser/parser.h"
#include "lexer/lexer.h"

using namespace nova;

// Helper function to generate C code
codegen::GeneratedCode generateCCode(const std::string& source) {
    Lexer lexer(source, "test.nv");
    std::vector<Token> tokens = lexer.tokenize();
    Parser parser(tokens);
    auto program = parser.parse();
    
    SemanticAnalyzer analyzer;
    analyzer.analyze(program);
    
    IRGenerator irGen;
    auto irModule = irGen.generate(program);
    
    codegen::CCodeGenerator codeGen;
    return codeGen.generate(irModule);
}

// ============================================================================
// Code Generator Construction Tests
// ============================================================================

TEST_CASE("Code generator can be constructed", "[codegen][construction]") {
    REQUIRE_NOTHROW(codegen::CCodeGenerator());
}

TEST_CASE("Code generator factory creates correct type", "[codegen][construction]") {
    auto generator = codegen::CodeGeneratorFactory::create(codegen::TargetPlatform::C_CODE);
    
    REQUIRE(generator != nullptr);
}

// ============================================================================
// Generated Code Structure Tests
// ============================================================================

TEST_CASE("Generated code has content", "[codegen][output]") {
    auto code = generateCCode("fn foo() -> void { }");
    
    CHECK_FALSE(code.code.empty());
    CHECK_FALSE(code.filename.empty());
    CHECK(code.language == "C");
}

TEST_CASE("Generated code has correct filename", "[codegen][output]") {
    auto code = generateCCode("fn foo() -> void { }");
    
    CHECK(code.filename.find(".c") != std::string::npos);
}

TEST_CASE("Generated code can have custom filename", "[codegen][output]") {
    Lexer lexer("fn foo() -> void { }", "test.nv");
    std::vector<Token> tokens = lexer.tokenize();
    Parser parser(tokens);
    auto program = parser.parse();
    
    SemanticAnalyzer analyzer;
    analyzer.analyze(program);
    
    IRGenerator irGen;
    auto irModule = irGen.generate(program);
    
    codegen::CCodeGenerator codeGen;
    codeGen.setOutputFile("custom.c");
    auto code = codeGen.generate(irModule);
    
    CHECK(code.filename == "custom.c");
}

// ============================================================================
// Header Generation Tests
// ============================================================================

TEST_CASE("Generated code includes standard headers", "[codegen][headers]") {
    auto code = generateCCode("fn foo() -> void { }");
    
    CHECK(code.code.find("#include <stdio.h>") != std::string::npos);
    CHECK(code.code.find("#include <stdlib.h>") != std::string::npos);
    CHECK(code.code.find("#include <string.h>") != std::string::npos);
    CHECK(code.code.find("#include <stdbool.h>") != std::string::npos);
}

TEST_CASE("Generated code has compiler comment", "[codegen][headers]") {
    auto code = generateCCode("fn foo() -> void { }");
    
    CHECK(code.code.find("Generated by Nova Compiler") != std::string::npos);
}

// ============================================================================
// Function Generation Tests
// ============================================================================

TEST_CASE("Generated code contains function definition", "[codegen][functions]") {
    auto code = generateCCode("fn foo() -> void { }");
    
    CHECK(code.code.find("void foo()") != std::string::npos);
}

TEST_CASE("Generated code handles function parameters", "[codegen][functions]") {
    auto code = generateCCode("fn add(a: int, b: int) -> int { return a + b; }");
    
    CHECK(code.code.find("int add(int a, int b)") != std::string::npos);
}

TEST_CASE("Generated code handles return types", "[codegen][functions]") {
    auto code1 = generateCCode("fn getInt() -> int { return 0; }");
    CHECK(code1.code.find("int getInt()") != std::string::npos);
    
    auto code2 = generateCCode("fn getFloat() -> float { return 0.0; }");
    CHECK(code2.code.find("double getFloat()") != std::string::npos);
    
    auto code3 = generateCCode("fn getBool() -> bool { return true; }");
    CHECK(code3.code.find("bool getBool()") != std::string::npos);
}

TEST_CASE("Generated code handles multiple functions", "[codegen][functions]") {
    auto code = generateCCode(
        "fn foo() -> void { }\n"
        "fn bar() -> void { }\n"
    );
    
    CHECK(code.code.find("void foo()") != std::string::npos);
    CHECK(code.code.find("void bar()") != std::string::npos);
}

// ============================================================================
// Type Translation Tests
// ============================================================================

TEST_CASE("Generated code translates int type", "[codegen][types]") {
    auto code = generateCCode("let x: int = 42;");
    
    CHECK(code.code.find("int") != std::string::npos);
}

TEST_CASE("Generated code translates float type", "[codegen][types]") {
    auto code = generateCCode("let x: float = 3.14;");
    
    CHECK(code.code.find("double") != std::string::npos);
}

TEST_CASE("Generated code translates bool type", "[codegen][types]") {
    auto code = generateCCode("let x: bool = true;");
    
    CHECK(code.code.find("bool") != std::string::npos);
}

TEST_CASE("Generated code translates string type", "[codegen][types]") {
    auto code = generateCCode("let s: string = \"hello\";");
    
    CHECK(code.code.find("char*") != std::string::npos);
}

TEST_CASE("Generated code translates void type", "[codegen][types]") {
    auto code = generateCCode("fn foo() -> void { }");
    
    CHECK(code.code.find("void") != std::string::npos);
}

// ============================================================================
// Arithmetic Operation Tests
// ============================================================================

TEST_CASE("Generated code handles addition", "[codegen][arithmetic]") {
    auto code = generateCCode("fn add(a: int, b: int) -> int { return a + b; }");
    
    CHECK(code.code.find("+") != std::string::npos);
}

TEST_CASE("Generated code handles subtraction", "[codegen][arithmetic]") {
    auto code = generateCCode("fn sub(a: int, b: int) -> int { return a - b; }");
    
    CHECK(code.code.find("-") != std::string::npos);
}

TEST_CASE("Generated code handles multiplication", "[codegen][arithmetic]") {
    auto code = generateCCode("fn mul(a: int, b: int) -> int { return a * b; }");
    
    CHECK(code.code.find("*") != std::string::npos);
}

TEST_CASE("Generated code handles division", "[codegen][arithmetic]") {
    auto code = generateCCode("fn div(a: int, b: int) -> int { return a / b; }");
    
    CHECK(code.code.find("/") != std::string::npos);
}

TEST_CASE("Generated code handles modulo", "[codegen][arithmetic]") {
    auto code = generateCCode("fn mod(a: int, b: int) -> int { return a % b; }");
    
    CHECK(code.code.find("%") != std::string::npos);
}

// ============================================================================
// Comparison Operation Tests
// ============================================================================

TEST_CASE("Generated code handles equality", "[codegen][comparison]") {
    auto code = generateCCode("fn eq(a: int, b: int) -> bool { return a == b; }");
    
    CHECK(code.code.find("==") != std::string::npos);
}

TEST_CASE("Generated code handles inequality", "[codegen][comparison]") {
    auto code = generateCCode("fn ne(a: int, b: int) -> bool { return a != b; }");
    
    CHECK(code.code.find("!=") != std::string::npos);
}

TEST_CASE("Generated code handles less-than", "[codegen][comparison]") {
    auto code = generateCCode("fn lt(a: int, b: int) -> bool { return a < b; }");
    
    CHECK(code.code.find("<") != std::string::npos);
}

TEST_CASE("Generated code handles greater-than", "[codegen][comparison]") {
    auto code = generateCCode("fn gt(a: int, b: int) -> bool { return a > b; }");
    
    CHECK(code.code.find(">") != std::string::npos);
}

TEST_CASE("Generated code handles less-equal", "[codegen][comparison]") {
    auto code = generateCCode("fn le(a: int, b: int) -> bool { return a <= b; }");
    
    CHECK(code.code.find("<=") != std::string::npos);
}

TEST_CASE("Generated code handles greater-equal", "[codegen][comparison]") {
    auto code = generateCCode("fn ge(a: int, b: int) -> bool { return a >= b; }");
    
    CHECK(code.code.find(">=") != std::string::npos);
}

// ============================================================================
// Logical Operation Tests
// ============================================================================

TEST_CASE("Generated code handles logical AND", "[codegen][logical]") {
    auto code = generateCCode("fn andOp(a: bool, b: bool) -> bool { return a && b; }");
    
    CHECK(code.code.find("&&") != std::string::npos);
}

TEST_CASE("Generated code handles logical OR", "[codegen][logical]") {
    auto code = generateCCode("fn orOp(a: bool, b: bool) -> bool { return a || b; }");
    
    CHECK(code.code.find("||") != std::string::npos);
}

TEST_CASE("Generated code handles logical NOT", "[codegen][logical]") {
    auto code = generateCCode("fn notOp(a: bool) -> bool { return !a; }");
    
    CHECK(code.code.find("!") != std::string::npos);
}

// ============================================================================
// Control Flow Tests
// ============================================================================

TEST_CASE("Generated code handles return statement", "[codegen][control-flow]") {
    auto code = generateCCode("fn foo() -> int { return 42; }");
    
    CHECK(code.code.find("return") != std::string::npos);
}

TEST_CASE("Generated code handles if statement", "[codegen][control-flow]") {
    auto code = generateCCode(
        "fn abs(x: int) -> int {\n"
        "    if (x < 0) {\n"
        "        return -x;\n"
        "    }\n"
        "    return x;\n"
        "}\n"
    );
    
    CHECK(code.code.find("if") != std::string::npos);
    CHECK(code.code.find("goto") != std::string::npos);
}

TEST_CASE("Generated code handles while loop", "[codegen][control-flow]") {
    auto code = generateCCode(
        "fn countdown(n: int) -> int {\n"
        "    while (n > 0) {\n"
        "        n = n - 1;\n"
        "    }\n"
        "    return n;\n"
        "}\n"
    );
    
    CHECK(code.code.find("while") != std::string::npos);
}

// ============================================================================
// Function Call Tests
// ============================================================================

TEST_CASE("Generated code handles function calls", "[codegen][calls]") {
    auto code = generateCCode(
        "fn square(x: int) -> int {\n"
        "    return x * x;\n"
        "}\n"
        "fn test() -> int {\n"
        "    return square(5);\n"
        "}\n"
    );
    
    CHECK(code.code.find("square(5)") != std::string::npos);
}

TEST_CASE("Generated code handles nested function calls", "[codegen][calls]") {
    auto code = generateCCode(
        "fn add(a: int, b: int) -> int { return a + b; }\n"
        "fn test() -> int { return add(add(1, 2), 3); }\n"
    );
    
    CHECK(code.code.find("add(") != std::string::npos);
}

// ============================================================================
// Variable Declaration Tests
// ============================================================================

TEST_CASE("Generated code declares temporary variables", "[codegen][variables]") {
    auto code = generateCCode("fn add(a: int, b: int) -> int { return a + b; }");
    
    CHECK(code.code.find("_t_") != std::string::npos);
}

TEST_CASE("Generated code handles global variables", "[codegen][variables]") {
    auto code = generateCCode("let x: int = 42;");
    
    CHECK(code.code.find("int x") != std::string::npos);
}

// ============================================================================
// Code Quality Tests
// ============================================================================

TEST_CASE("Generated code is compilable C code", "[codegen][quality]") {
    auto code = generateCCode(
        "fn add(a: int, b: int) -> int {\n"
        "    return a + b;\n"
        "}\n"
    );
    
    // Check for basic C structure
    CHECK(code.code.find("{") != std::string::npos);
    CHECK(code.code.find("}") != std::string::npos);
    CHECK(code.code.find(";") != std::string::npos);
}

TEST_CASE("Generated code has proper indentation", "[codegen][quality]") {
    auto code = generateCCode(
        "fn foo() -> void {\n"
        "    return;\n"
        "}\n"
    );
    
    // Check that code is formatted
    CHECK(code.code.find("    ") != std::string::npos);  // Has indentation
}

TEST_CASE("Generated code has comments", "[codegen][quality]") {
    auto code = generateCCode("fn foo() -> void { }");
    
    CHECK(code.code.find("/*") != std::string::npos);
    CHECK(code.code.find("*/") != std::string::npos);
}

// ============================================================================
// Integration Tests
// ============================================================================

TEST_CASE("Generated code for complete program", "[codegen][integration]") {
    auto code = generateCCode(
        "fn factorial(n: int) -> int {\n"
        "    if (n <= 1) {\n"
        "        return 1;\n"
        "    }\n"
        "    return n * factorial(n - 1);\n"
        "}\n"
        "\n"
        "fn main() -> void {\n"
        "    let result: int = factorial(5);\n"
        "}\n"
    );
    
    CHECK_FALSE(code.code.empty());
    CHECK(code.code.find("factorial") != std::string::npos);
    CHECK(code.code.find("main") != std::string::npos);
}

TEST_CASE("Generated code for multiple functions with calls", "[codegen][integration]") {
    auto code = generateCCode(
        "fn square(x: int) -> int { return x * x; }\n"
        "fn sumOfSquares(a: int, b: int) -> int {\n"
        "    return square(a) + square(b);\n"
        "}\n"
    );
    
    CHECK(code.code.find("square") != std::string::npos);
    CHECK(code.code.find("sumOfSquares") != std::string::npos);
    CHECK(code.code.find("+") != std::string::npos);
}
