
/* Generated by Nova Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

int add(int a, int b) {

    /* Block: entry */
    entry:
        _t_t0 = a + b;
        return _t_t0;
}

